## Section A: Data Structures & Control Structures

### 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [23]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]


In [24]:

# append
numbers.append(60)
print("After append:", numbers)

# extend
numbers.extend([70, 80])
print("After extend:", numbers)


After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]


In [25]:

# insert
numbers.insert(2, 25)  # insert at index 2
print("After insert:", numbers)

# remove
numbers.remove(40)  # removes the first occurrence of 40
print("After remove:", numbers)


After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]


In [26]:

# pop
popped = numbers.pop()  # removes last element
print("After pop:", numbers, "| Popped element:", popped)

# index
idx = numbers.index(25)
print("Index of 25:", idx)


After pop: [10, 20, 25, 30, 50, 60, 70] | Popped element: 80
Index of 25: 2


In [27]:

# count
cnt = numbers.count(20)
print("Count of 20:", cnt)

# sort
numbers.sort()
print("After sort:", numbers)


Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]


In [28]:

# reverse
numbers.reverse()
print("After reverse:", numbers)


After reverse: [70, 60, 50, 30, 25, 20, 10]


In [29]:

# clear
numbers.clear()
print("After clear:", numbers)


After clear: []


### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [30]:
# Create a tuple with 3 student names
students = ("Alice", "Bob", "Charlie")
print("Original Tuple:", students)


Original Tuple: ('Alice', 'Bob', 'Charlie')


In [31]:
# Convert the tuple to a list
students_list = list(students)

# Change the second name in the list
students_list[1] = "David"

# Convert the list back to a tuple
students = tuple(students_list)

print("Modified Tuple:", students)

Modified Tuple: ('Alice', 'David', 'Charlie')


 Tuples in Python are immutable, which means once they are created, their elements cannot be modified, added, or removed.

That’s why you cannot change "Bob" to "David" directly.

If you really want to modify it, you’d have to convert the tuple into a list, make the change, and then convert it back to a tuple

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [32]:

numbers = {1, 2, 2, 3, 4, 4, 5}


print("Set:", numbers)


Set: {1, 2, 3, 4, 5}


A set in Python is an unordered collection of unique elements.

When you add duplicate values (2, 4 in this case), Python removes the duplicates automatically.

That’s why the output only shows {1, 2, 3, 4, 5} without repetitions.

### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [33]:

person = {
    "name": "John",
    "age": 25,
    "city": "Mumbai"
}


In [34]:

# Update the age
person["age"] = 26

# Add a new key 'email'
person["email"] = "john@example.com"

# Print final dictionary
print("Final Dictionary:", person)


Final Dictionary: {'name': 'John', 'age': 26, 'city': 'Mumbai', 'email': 'john@example.com'}


### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [35]:

age = 17

# Check eligibility
if age >= 18:
    print("Eligible to vote ")
else:
    print("Not eligible to vote ")


Not eligible to vote 


### 6.	Given a 'marks' variable, print the grade:
### - 90 and above: 'A'
### - 75–89: 'B'
### - 50–74: 'C'
### - Below 50: 'Fail'


In [36]:
# Grading system

marks = 82

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Grade: B


### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [37]:


num = -5

if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("The number is Zero")
else:
    print("Negative number")


Negative number


## Section B: Numpy

### 8.	Create:
### - A scalar using np.array(5)
### - A 1D array with values 1 to 5
### - A 2D array (2x3) with values from 10 to 60 in steps of 10


In [38]:
import numpy as np

scalar = np.array(5)
print("Scalar:\n", scalar)


array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", array_1d)

array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("\n2D Array (2x3):\n", array_2d)


Scalar:
 5

1D Array:
 [1 2 3 4 5]

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [39]:

random_array = np.random.randint(0, 101, size=(4,4))
print("\n4x4 Random Array:\n", random_array)



4x4 Random Array:
 [[44 91  3 52]
 [46 61 35 27]
 [96 91 80 23]
 [ 5 34 12 60]]


### 10. Convert NumPy Array to Pandas DataFrame

In [40]:
import pandas as pd
array_3x3 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


df = pd.DataFrame(array_3x3, columns=['A','B','C'])
print("\nDataFrame:\n", df)



DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
### - Use .info(), .describe()
### - Select 'Name' and 'City' columns
### - Drop 'City' column
### - Fill any missing values in 'Salary' column with the mean
### - Remove any duplicate rows


In [41]:
import pandas as pd
import numpy as np


data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva",
             "Frank", "Grace", "Hannah", "Ivan", "Jack"],
    "Age": [25, 30, 22, 28, 35, 40, 29, 31, 27, 30],
    "City": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Pune",
             "Delhi", "Kolkata", "Bangalore", "Mumbai", "Delhi"],
    "Salary": [50000, 60000, np.nan, 55000, 70000,
               60000, 65000, 55000, 50000, 60000]
}


In [42]:

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

print("\nDataFrame Info:")
print(df.info())

print("\nDataFrame Description:")
print(df.describe())


Original DataFrame:
       Name  Age       City   Salary
0    Alice   25     Mumbai  50000.0
1      Bob   30      Delhi  60000.0
2  Charlie   22  Bangalore      NaN
3    David   28    Chennai  55000.0
4      Eva   35       Pune  70000.0
5    Frank   40      Delhi  60000.0
6    Grace   29    Kolkata  65000.0
7   Hannah   31  Bangalore  55000.0
8     Ivan   27     Mumbai  50000.0
9     Jack   30      Delhi  60000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame Description:
             Age        Salary
count  10.000000      9.000000
mean   29.700000  58333.333333
std     5.034327   6614.378278
min    22.000000  50000

In [43]:


print("\nSelected Columns (Name, City):\n", df[["Name", "City"]])


df_dropped = df.drop(columns=["City"])
print("\nAfter Dropping 'City' column:\n", df_dropped)



Selected Columns (Name, City):
       Name       City
0    Alice     Mumbai
1      Bob      Delhi
2  Charlie  Bangalore
3    David    Chennai
4      Eva       Pune
5    Frank      Delhi
6    Grace    Kolkata
7   Hannah  Bangalore
8     Ivan     Mumbai
9     Jack      Delhi

After Dropping 'City' column:
       Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   22      NaN
3    David   28  55000.0
4      Eva   35  70000.0
5    Frank   40  60000.0
6    Grace   29  65000.0
7   Hannah   31  55000.0
8     Ivan   27  50000.0
9     Jack   30  60000.0


In [44]:


df["Salary"].fillna(df["Salary"].mean(), inplace=True)
print("\nAfter Filling Missing Salary with Mean:\n", df)


df_no_duplicates = df.drop_duplicates()
print("\nAfter Removing Duplicates:\n", df_no_duplicates)



After Filling Missing Salary with Mean:
       Name  Age       City        Salary
0    Alice   25     Mumbai  50000.000000
1      Bob   30      Delhi  60000.000000
2  Charlie   22  Bangalore  58333.333333
3    David   28    Chennai  55000.000000
4      Eva   35       Pune  70000.000000
5    Frank   40      Delhi  60000.000000
6    Grace   29    Kolkata  65000.000000
7   Hannah   31  Bangalore  55000.000000
8     Ivan   27     Mumbai  50000.000000
9     Jack   30      Delhi  60000.000000

After Removing Duplicates:
       Name  Age       City        Salary
0    Alice   25     Mumbai  50000.000000
1      Bob   30      Delhi  60000.000000
2  Charlie   22  Bangalore  58333.333333
3    David   28    Chennai  55000.000000
4      Eva   35       Pune  70000.000000
5    Frank   40      Delhi  60000.000000
6    Grace   29    Kolkata  65000.000000
7   Hannah   31  Bangalore  55000.000000
8     Ivan   27     Mumbai  50000.000000
9     Jack   30      Delhi  60000.000000


/tmp/ipython-input-4106200194.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)
